version: '3.8'
services:
  server:
    image: connectify_api
    container_name: connectify_api
    depends_on:
      - postgres
    build: ./
    ports:
      - 3000:3000
    develop:
      watch:
      - path: ./
        target: ./usr/src/app
        action: sync
      - path: ./package*.json
        action: rebuild
    networks:
       connectify:
        ipv4_address: 172.3.0.5

  postgres:
    image: postgres:latest
    container_name: connectify_api_db
    restart: always
    volumes:
     - connectify:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: connectify
    networks:
       connectify:
        ipv4_address: 172.3.0.4


  pgadmin: 
    image: dpage/pgadmin4:latest
    container_name: connectify_api_pgadmin
    depends_on:
      - postgres
    ports:
      - "5050:5050"

    environment:
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_DEFAULT_EMAIL: jrpogiyanyow@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      SECURE_PROXY_SSL_HEADER : None
      SESSION_COOKIE_SECURE : False
      CSRF_COOKIE_SECURE : False
      SERVER_MODE : False
    networks:
       connectify:
        ipv4_address: 172.3.0.6

networks:
  connectify:
    driver: bridge
    ipam:
      config:
        - subnet: 172.3.0.0/16

volumes:
  connectify:
     name: connectify
     driver: local
  